'use client'

import Image from 'next/image'

export function Footer() {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <footer className="bg-black text-white border-t-4 border-accent">
      <div className="container mx-auto px-8 md:px-16 lg:px-24 max-w-7xl py-16">
        <div className="grid md:grid-cols-3 gap-12 mb-12">
          <div>
            <Image
              src="https://static.wixstatic.com/media/372943_ce0bf21ba97b40a1a99f20b6aa567631~mv2.png"
              alt="Mohzie"
              width={120}
              height={36}
              className="h-10 w-auto mb-6 brightness-0 invert"
            />
            <p className="text-sm leading-relaxed text-white/80">
              Transforming chaotic email threads into structured, accountable workflows with compliance-grade governance.
            </p>
          </div>

          <div>
            <h4 className="text-sm font-bold uppercase tracking-wider mb-6 text-accent">
              Document Sections
            </h4>
            <ul className="space-y-3">
              {[
                { label: 'Platform Overview', id: 'overview' },
                { label: 'Feature Buckets', id: 'features' },
                { label: 'Target Industries', id: 'industries' },
                { label: 'Market Comparison', id: 'comparison' },
                { label: 'ROI Framework', id: 'roi' },
                { label: 'GTM Strategy', id: 'gtm' },
              ].map((section) => (
                <li key={section.id}>
                  <button
                    onClick={() => {
                      const element = document.getElementById(section.id)
                      if (element) {
                        element.scrollIntoView({ behavior: 'smooth' })
                      }
                    }}
                    className="text-sm text-white/80 hover:text-accent transition-colors cursor-pointer"
                  >
                    {section.label}
                  </button>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4 className="text-sm font-bold uppercase tracking-wider mb-6 text-accent">
              Key Insights
            </h4>
            <ul className="space-y-3 text-sm text-white/80">
              <li className="flex items-start gap-2">
                <div className="w-1 h-1 bg-accent mt-2 flex-shrink-0" />
                <span>RACI-based productivity + compliance-grade audit trails</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-1 h-1 bg-accent mt-2 flex-shrink-0" />
                <span>Dual market approach: PLG + SLG</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-1 h-1 bg-accent mt-2 flex-shrink-0" />
                <span>Bridges productivity tools & compliance platforms</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-1 h-1 bg-accent mt-2 flex-shrink-0" />
                <span>30-40% reduction in email processing time</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="border-t border-white/20 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-sm text-white/60">
              <span className="font-medium">Transforming Email Chaos into Structured Accountability</span> — Last Updated February 2026
            </div>
            
            <button
              onClick={scrollToTop}
              className="px-6 py-2 border border-white text-white hover:bg-accent hover:border-accent transition-all duration-300 text-sm font-bold uppercase tracking-wide cursor-pointer"
            >
              Back to Top
            </button>
          </div>
          
          <div className="text-xs text-white/40 mt-6 text-center">
            Generated by Superagent
          </div>
        </div>
      </div>
    </footer>
  )
}
